steps:
  - name: maven:3.6.3-jdk-11
    entrypoint: 'mvn'
    args: ['verify', 'sonar:sonar', '-Dsonar.projectKey=GCP-GIT',-Donar.organization=dubcygoat '-Dsonar.host.url=http://sonarqube:9000', '-Dsonar.login=9d89af6454490305ba9a5686fe61a57cfb405388']
options:
      logging: CLOUD_LOGGING_ONLY